In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
import warnings

warnings.filterwarnings('ignore')

In [7]:
bank_data = pd.read_csv('..\..\dataset\BankChurners.csv')
# bank_data.head()


# data preprocessing
# bank_data['Attrition_Flag'] = bank_data['Attrition_Flag'].replace({'Existing Customer': 0, 'Attrited Customer': 1}, inplace=True)
bank_data['Attrition_Flag'].replace({'Existing Customer': 0, 'Attrited Customer': 1}, inplace=True)
bank_data['Gender'].replace({'M':1, 'F':0}, inplace=True)
bank_data['Education_Level'].replace({'Unknown':0, 'Uneducated':1, 'High School':2, 'College':3, 
                                                                        'Graduate':4, 'Post-Graduate':5, 'Doctorate':6}, inplace=True)
bank_data['Marital_Status'].replace({'Unknown':0, 'Divorced':1, 'Married':2, 'Single':3}, inplace=True)
bank_data['Income_Category'].replace({'Unknown':0, 'Less than $40K':1, '$40K - $60K':2, '$60K - $80K':3,
                                                                       '$80K - $120K':4, '$120K +':5}, inplace=True)
bank_data['Card_Category'].replace({'Blue':0, 'Silver':1, 'Gold':2, 'Platinum':3}, inplace=True)

bank_data.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,0,45,1,3,2,2,3,0,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,0,49,0,5,4,3,1,0,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,0,51,1,3,4,2,4,0,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,0,40,0,4,2,0,1,0,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,0,40,1,3,1,2,3,0,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [16]:
# data standard
X = bank_data.drop(columns=['Attrition_Flag'], axis=1)
y = bank_data['Attrition_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# cross valid
scores = cross_val_score(RandomForestClassifier(), X_train, y_train, cv=10, scoring='accuracy')
print('the accuracy of 10 cv: ', scores)

the accuracy of 10 cv:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [ ]:
# Parameter Tuning: RandomForestClassifier()
mdoel_rf = RandomForestClassifier()